### ISSUE TITLE
Can't login after install in docker

### ISSUE THREAD

**Issue by ruslansharipov2304** [azimuttapp/azimutt#346]
Hello! Following the instructions, I installed Azimutt locally in Docker. 
env file
`
PHX_SERVER=true
PHX_HOST=localhost
PORT=4000
SECRET_KEY_BASE=1wOVZ9rWAqPcbVZdilZzBPLXFKNrUmLUzX0q9Z02LpOy2jVWZwa6ee4fU81tuN+W
DATABASE_URL=postgresql://postgres:postgres@localhost/azimutt_dev
FILE_STORAGE_ADAPTER=local
AUTH_PASSWORD=true
`

docker-compose file:
`
services:
  database:
    image: postgres
    restart: always
    container_name: azimutt-db
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment: # Used by the postgres image to setup a default user. For security reason, you should avoid using the postgres user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: azimutt_dev
  backend:
    container_name: azimutt-backend
    platform: linux/amd64
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports: # Docker need to expose ports for you to access your app.
      - 4000:4000
    env_file: .env
    environment:
      DATABASE_URL: "ecto://postgres:postgres@database/azimutt_dev" # Template : "ecto://db_user:db_password@ip_or_compose_service_name/db_name"
      SECRET_KEY_BASE: "1wOVZ9rWAqPcbVZdilZzBPLXFKNrUmLUzX0q9Z02LpOy2jVWZwa6ee4fU81tuN+W" # Can literally be anything, but generally generated randomly by tools like mix phx.gen.secret
volumes:
  pg-data:
`

run : docker-compose up -d

After login (admin@azimutt.app  password - admin), I get an 403 error
Next, I’m connect to azimutt_dev database - table public.users is empty. 
When I try Register (from main page), I also get an 403 error

**Comment by ssqlone** [comment]
```yaml
services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=azimutt-user
      - POSTGRES_DB=azimutt
    volumes:
      - 'azimutt-db:/var/lib/postgresql/data'
    networks:
      - azimutt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 60s
      timeout: 20s
      retries: 5
  azimutt:
    container_name: azimutt
    platform: linux/amd64
    image: ghcr.io/azimuttapp/azimutt:main
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SENTRY=false
      - PHX_SERVER=true
      - 'PHX_HOST=https://azimutt.example.com'
      - PORT=4000
      - 'DATABASE_URL=ecto://azimutt-user:changeme@postgres/azimutt'
      - 'SECRET_KEY_BASE=secret-key-base'
      - AUTH_PASSWORD=false
      - FILE_STORAGE_ADAPTER=local
      - SKIP_ONBOARDING_FUNNEL=true
      - SKIP_EMAIL_CONFIRMATION=true
      - PUBLIC_SITE=true
    networks:
      - azimutt-network
      - proxy
    expose:
      - 4000
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/4000' || exit 1"]
      interval: 60s
      timeout: 20s
      retries: 5
networks:
  azimutt-network:
  proxy:
    external: true
volumes:
  azimutt-db:
```
try this
